os: linux
dist: xenial
language: python
python:
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install -r requirements.txt
before_script:
  - pip install -r requirements-dev.txt
script:
  - tox
after_success:
  - coveralls
